### ISSUE TITLE
TypeError: read() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by xzl0034** [SegataLab/PanPhlAn_pangenome_exporter#1]
I was using the pangenome_exporter to build a pan genome. 
The code I used was:
python /drive1/user/apps/PanPhlAn_pangenome_exporter/panphlan_exporter.py -n 28 -c Collinsella_aerofaciens -d /drive1/user/reference/PanPhlAn -p /drive1/user/reference/PanPhlAn/ncbi_dataset/Collinsella_aerofaciens/pan -i /drive1/user/reference/PanPhlAn/ncbi_dataset/Collinsella_aerofaciens/fna

I got the following error:
```
Traceback (most recent call last):
  File "/drive1/user/apps/PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 520, in <module>
    panphlan_exporter(args.input, args.tmp, args.output, args.clade_name, args.nprocs, args.db_path)
  File "/drive1/user/apps/PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 501, in panphlan_exporter
    write_panphlan_tsv(inputdir, tmp_dir, ppa_outdir, clade_name, contigs_names_dict, contigs_names_dict_prokka, extend_pangenome)
  File "/drive1/user/apps/PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 425, in write_panphlan_tsv
    for rec in GFF.parse(gff_file, limit_info=dict(gff_type = ['CDS'])):
  File "/home/user/miniconda2/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 746, in parse
    target_lines):
  File "/home/user/miniconda2/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/home/user/miniconda2/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/home/user/miniconda2/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/home/user/miniconda2/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/home/user/miniconda2/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/home/user/miniconda2/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/home/user/miniconda2/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/home/user/miniconda2/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 51, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given
```

Here is the infor about the package I have:

prokka 1.14.6
MMseqs2 Version: 13.45111
diamond version 2.0.8
bowtie2 version 2.4.2

How should I fix the problem?

Thanks.

**Comment by leonarDubois** [comment]
Hello, 

It is actually a known issue depending on the version of BCBio GFF
Have a look at [this issue](https://github.com/SegataLab/cmseq/issues/4) for details
Basically you just need Biopython with a version older or equal to 1.76. otherwise this happen.

**Comment by xzl0034** [comment]
Thanks!
I installed python 1.76. 
Now it seems working.
