### ISSUE TITLE
getting 'get_unannotated_proteins' error while building pangenome

### ISSUE THREAD

**Issue by drelo** [SegataLab/PanPhlAn_pangenome_exporter#3]
Dear I came back to using this software after getting a better idea of the variability within the group (and selecting the metagenomes to do the search later on)
I did a demo building a small pangenome with only 4 genomes and the PanPhlAn exporter worked fine. Now trying to scale it up to 34 genomes I found this error when trying to build it. 
```
Tue Nov 23 01:20:21 2021 Done.
Tue Nov 23 01:20:21 2021 Clustering unnanotated proteins at UniRef90 level...Traceback (most recent call last):
  File "./PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 520, in <module>
    panphlan_exporter(args.input, args.tmp, args.output, args.clade_name, args.nprocs, args.db_path)
  File "./PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 489, in panphlan_exporter
    get_unannotated_proteins(inputdir, tmp_dir, '90')
  File "./PanPhlAn_pangenome_exporter/panphlan_exporter.py", line 135, in get_unannotated_proteins
    with open(os.path.join(outputdir, 'uniref', genome_name, genome_name + '.faa'), 'r') as read_fasta:
FileNotFoundError: [Errno 2] No such file or directory: 'temp0/tmp/uniref/25721_2#132/25721_2#132.faa'
```

Maybe it is due I am including representatives of a divergent clade I will try removing it and rerun this with just 30 representatives.

[Here is the whole log](https://github.com/SegataLab/PanPhlAn_pangenome_exporter/files/7589191/ERROR.txt)

I am using a cluster with in a fresh install of the _pangenome_exporter_ 
[Here is the environment for it ](https://github.com/SegataLab/PanPhlAn_pangenome_exporter/files/7589160/centos.txt)

Thanks for your help

**Comment by drelo** [comment]
My bad, I eliminated `# `and `_` from the genome filenames and it worked fine. Closing now.
